<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo ASSET_SAYA ?>surat/style3.css" />
    <title>Laporan Kamar Terfavorite</title>
	<script src="<?php echo base_url('assets/js/highchart/js/highcharts.js') ?>"></script>
	<script src="<?php echo base_url('assets/js/highchart/js/modules/exporting.js') ?>"></script>
	<script src="<?php echo base_url('assets/js/highchart/js/modules/drilldown.js') ?>"></script>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img width="400" src="<?php echo ASSET_SAYA ?>/travelium/img/icon_hotelgarudawira.png" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
					<center>
						<p style="font-weight:none;font-size:14pt">LAPORAN KAMAR TERFAVORITE</br>
						Periode : <?php echo date("F",strtotime(date("d")."-".$bulan."-".$tahun))." ".$tahun;?></p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td>&nbsp; No</th>
							<td style="text-align:left;">&nbsp; Nama Kamar</td>
							<td style="text-align:left;">&nbsp; Total Reservasi</td>
						</tr>
						<?php
						$subtot = 0;
						foreach($listData as $value){
							//$subtot = $subtot + $value['total_harga_reservasi'];
							$no++;
						 ?>
						<tr class="isi-colom">
							<td style="font-size:8pt;">&nbsp; <?php echo $no;?></td>
							<td style="font-size:8pt; text-align:left;">&nbsp; <?php echo $value['nama_kamar'] ?></td>
							<td style="font-size:8pt; text-align:left;">&nbsp; <?php echo $value['total_kamar']; ?></td>
						</tr>
                        <?php } ?>
					</table>
					<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
					
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>