<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo ASSET_SAYA ?>surat/style3.css" />
    <title>Laporan Reservasi Bulanan</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img width="400" src="<?php echo ASSET_SAYA ?>/travelium/img/icon_hotelgarudawira.png" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
					<center>
						<p style="font-weight:none;font-size:14pt">LAPORAN DATA RESERVASI</br>
						Periode : <?php echo date("F",strtotime(date("d")."-".$bulan."-".$tahun))." ".$tahun;?></p>
					</center>
                    <table class="tb1" style="width: 100%;">
						<tr>
							<td>No</th>
							<td style="text-align:left;">No. Transaksi</td>
							<td style="text-align:left;">Tgl. Transaksi</td>
							<td style="text-align:left;">Atas Nama</td>
							<td style="text-align:left;">Total Kamar</td>
							<td style="text-align:left;">Tgl. Chekin</td>
							<td style="text-align:left;">Tgl. Chekout</td>
							<td style="text-align:left;">Total Bayar</td>
						</tr>
						<?php  
						$subtot = 0;
						foreach($listData as $value){
							$subtot = $subtot + $value['total_harga_reservasi'];
							$no++;
						 ?>
						<tr class="isi-colom">
							<td style="font-size:8pt;"><?php echo $no;?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo $value['id_reservasi'] ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo $value['tgltransaksi']; ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo $value['nama_lengkap']; ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo $value['total_kamar']; ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo date("d F Y",strtotime($value['tglcheckin'])); ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo date("d F Y",strtotime($value['tglcheckout'])); ?></td>
							<td style="font-size:8pt; text-align:left;"><?php echo "Rp. ".number_format($value['total_harga_reservasi'],0,'.','.'); ?></td>
						</tr>
                        <?php } ?>
						<tr class="isi-colom">
							<td style="font-size:8pt;text-align:right;"" colspan="6">Total&nbsp;</td>
							<td style="font-size:8pt;text-align:center;" ><?php echo $no;?> Data</td>
							<td style="font-size:8pt;text-align:left;" ><?php echo "Rp. ".number_format($subtot,0,'.','.'); ?></td>
						</tr>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>